### ISSUE TITLE
gnip_time_series.py should check for plots/ dir before starting

### ISSUE THREAD

**Issue by jrmontag** [DrSkippy/Gnip-Python-Search-API-Utilities#26]
When asked for time-series plots when the local ``plots/`` directory doesn't exist, the ``gnip_time_series.py`` script retrieves data and later crashes with an ``IOError``:

```bash
$ ./gnip_time_series.py -f "ces2016" -s"2015-12-01T00:00:00" -e"2016-01-08T00:00:00" -t -bhour
[    6816 bytes]   744 total activities retrieved...
Fetching page 2...
[    8328 bytes]   912 total activities retrieved...
/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
Traceback (most recent call last):
  File "./gnip_time_series.py", line 585, in <module>
    g.plots(ts)
  File "./gnip_time_series.py", line 501, in plots
    plt.savefig(os.path.join(PLOTS_PREFIX, '{}_{}.{}'.format(filter_prefix_name, "time_line", out_type)))
  File "/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2211, in print_figure
    **kwargs)
  File "/Users/jmontague/.virtualenvs/data-2.7-tw/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 526, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 2] No such file or directory: './plots/ces2016_time_line.png'
```

Perhaps we can either include that empty directory in the repo e.g. with just a readme file or catch and extend the error message with instructions. Alternatively, we could exit sooner (with a helpful error message) if we see that directory doesn't exist.

I realize that the repo readme says to make a directory called plots, but perhaps we can make it easier, still.

**Comment by DrSkippy** [comment]
Added a on both data and plots directories with the application exiting when they don't exist.
