### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by bigme666** [DrSkippy/Gnip-Python-Search-API-Utilities#37]
I just installed the package with all its dependencies and tryed to execute the sample code:

```
$ gnip_search.py -f"from:drskippy" -n500 links
Traceback (most recent call last):
  File "/home/gnip/gnip-support/support/Gnip-Python-Search-API-Utilities/testenv/bin/gnip_search.py", line 236, in <module>
    g = GnipSearchCMD()
  File "/home/gnip/gnip-support/support/Gnip-Python-Search-API-Utilities/testenv/bin/gnip_search.py", line 72, in __init__
    if "data-api.twitter.com" in self.stream_url:
TypeError: argument of type 'NoneType' is not iterable
```
these are my installed packages

cycler (0.10.0)
gapi (1.1.0)
gnacs (1.1.0)
matplotlib (1.5.3)
numpy (1.11.2)
pandas (0.19.1)
patsy (0.4.1)
pip (9.0.1)
pyparsing (2.1.10)
python-dateutil (2.6.0)
pytz (2016.7)
requests (2.12.1)
scipy (0.18.1)
setuptools (28.8.0)
six (1.10.0)
sngrams (0.2.0)
statsmodels (0.6.1)
ujson (1.35)
wheel (0.30.0a0)

and I'm using python 2.7

**Comment by jrmontag** [comment]
Hi @bigme666! Thanks for raising the issue. 

That exception (whose error message could definitely be easier to interpret) typically means that you don't have a stream URL set up. That can be done either through [the `.gnip` config file](https://github.com/DrSkippy/Gnip-Python-Search-API-Utilities#using-a-configuration-file), or [the `-l` command line option](https://github.com/DrSkippy/Gnip-Python-Search-API-Utilities#search-api).

Do you get the same behavior if you have one of those two set up?

**Comment by bigme666** [comment]
thank you for your answer! I just figured out what the problem was: I launched the app from a virtualenv and for some reason the environment variable pointing to the .gnip file was not set. As I set it manually the execution was ok. i think that maybe you should provide a custom error message if the environment variable GNIP_CONFIG_FILE is not set up correctly.

**Comment by jrmontag** [comment]
Glad you got it sorted out, @bigme666. Thanks for the feedback.

**Comment by jrmontag** [comment]
@DrSkippy if you want to close this specific Issue, I've added #38 to log this as a future enhancement.
