### ISSUE TITLE
Problem with "split" function

### ISSUE THREAD

**Issue by ciplipzip** [DrSkippy/Gnip-Python-Search-API-Utilities#43]
Hi.
When I execute:
./gnip_search.py -n 10 -f"The old apple revels in its authority" json

I obtain:
AttributeError: 'int' object has no attribute 'split'

./gnip_search.py -n 10 -f"The old apple revels in its authority" wordcount
Traceback (most recent call last):
  File "./gnip_search.py", line 237, in <module>
    print(g.get_result())
  File "./gnip_search.py", line 176, in get_result
    , hard_max=self.options.hard_max
  File "/home/user/Gnip-Python-Search-API-Utilities-master/search/results.py", line 64, in __init__
    , show_query = show_query
  File "/home/user/Gnip-Python-Search-API-Utilities-master/search/api.py", line 303, in execute
    tmp_list = self.twitter_parser.procRecordToList(rec)
  File "/home/user/ENV3/lib/python3.5/site-packages/acscsv/twitter_acs.py", line 78, in procRecordToList
    return self.get_output_list(d) 
  File "/home/user/ENV3/lib/python3.5/site-packages/acscsv/twitter_acs.py", line 91, in get_output_list
    output_list.append( Field_id(d).value )
  File "/home/user/ENV3/lib/python3.5/site-packages/acscsv/twitter_acs_fields.py", line 77, in __init__
    tmp = self.value.split(":")
AttributeError: 'int' object has no attribute 'split'

What is wrong?

Thanks

**Comment by DrSkippy** [comment]
I cannot reproduce.  Can you share some info on platform, os, terminal etc. to see if there is some debugging info we can add to help sort this out?  Thanks.

**Comment by ciplipzip** [comment]
Just to summarize.
1) I download both pip and GitHub versions and they give me different results! Since I assume I can trust GitHub, I'm using "./gnip_search.py" from inside the "Gnip-Python-Search-API-Utilities-master" folder obtained uncompressing GitHub clone download, and NOT "gnip_search.py" (that points to /usr/local/bin/gnip_search.py).
2) I'm on Ubuntu 16.04 64bit. Same error with both python 2.7 and 3.5 versions.
3) Additionally, if I perform the same command adding "-q" at the end, I have:
gnip_search.py -n 10 -f"The old apple revels in its authority" json -q
API query:
Traceback (most recent call last):
  File "/usr/local/bin/gnip_search.py", line 237, in <module>
    print(g.get_result())
  File "/usr/local/bin/gnip_search.py", line 176, in get_result
    , search_v2=self.options.search_v2
  File "/usr/local/lib/python2.7/dist-packages/search/results.py", line 65, in __init__
    , show_query = show_query
  File "/usr/local/lib/python2.7/dist-packages/search/api.py", line 276, in execute
    sys.stderr.write(self.rule_payload + '\n')
TypeError: unsupported operand type(s) for +: 'dict' and 'str'
This using pip version (gnip_search.py). Instead, if I execute the same query simulation within local path (./gnip_search.py), the command is executed correctly.

So, I guess I must use local version (GitHub one), but still have the "split" problem. I added a print of "self.value" inside /usr/local/lib/python2.7/dist-packages/acscsv/twitter_acs_fields.py and I have the Twitter_ID as the result before the split. That's why the next error I highlighted.

Could I have a problem with acscsv library?...
